/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vinoth' at '09/10/16 17:46' with Gradle 3.0
 *
 * @author vinoth, @date 09/10/16 17:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
